<?php
declare(strict_types=1);

$defaultAppStyles = [
    '/assets/css/views/app_shell.css',
];

$defaultAppScripts = [
    '/assets/js/views/app_shell/app_shell.js',
];

return [
    'landing_page' => [
        'path' => '/',
        'label' => 'Accueil',
        'title' => "Africo Cash | L'argent mobile sans frontières",
        'description' => 'Africo Cash connecte portefeuilles, banques, Mobile Money et retraits ATM sans carte dans une expérience financière moderne et sécurisée.',
        'view' => 'app/views/landing_page.php',
        'styles' => [
            '/assets/css/views/landing_page.css',
        ],
        'scripts' => [
            '/assets/js/views/landing_page/landing_page.service.js',
            '/assets/js/views/landing_page/landing_page.ui.js',
            '/assets/js/views/landing_page/landing_page.js',
        ],
    ],
    'login' => [
        'path' => '/connexion',
        'label' => 'Connexion',
        'title' => 'Connexion | Africo Cash',
        'description' => 'Connexion sécurisée Africo Cash par email et mot de passe.',
        'view' => 'app/views/login.php',
        'styles' => ['/assets/css/views/login.css'],
        'scripts' => ['/assets/js/views/login/login.js'],
    ],
    'register' => [
        'path' => '/inscription',
        'label' => 'Inscription',
        'title' => 'Inscription | Africo Cash',
        'description' => 'Ouverture de compte Africo Cash avec email et mot de passe.',
        'view' => 'app/views/register.php',
        'styles' => ['/assets/css/views/register.css'],
        'scripts' => ['/assets/js/views/register/register.js'],
    ],
    'onboarding' => [
        'path' => '/onboarding',
        'label' => 'Onboarding',
        'title' => 'Configuration du compte | Africo Cash',
        'description' => 'Configuration guidée du profil, des préférences et de la sécurité Africo Cash.',
        'view' => 'app/views/onboarding.php',
        'styles' => ['/assets/css/views/onboarding.css'],
        'scripts' => ['/assets/js/views/onboarding/onboarding.js'],
    ],
    'dashboard' => [
        'path' => '/dashboard',
        'label' => 'Tableau de bord',
        'icon' => 'fa-chart-pie',
        'title' => 'Tableau de bord | Africo Cash',
        'description' => 'Vue synthétique du portefeuille, des dépenses et des dernières transactions.',
        'view' => 'app/views/dashboard.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/dashboard.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/dashboard/dashboard.js']),
        'section' => 'app',
    ],
    'wallet' => [
        'path' => '/portefeuille',
        'label' => 'Portefeuille',
        'icon' => 'fa-wallet',
        'title' => 'Portefeuille | Africo Cash',
        'description' => 'Gestion des soldes multi-devises et mouvements du portefeuille Africo Cash.',
        'view' => 'app/views/wallet.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/wallet.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/wallet/wallet.js']),
        'section' => 'app',
    ],
    'transactions' => [
        'path' => '/transactions',
        'label' => 'Transactions',
        'icon' => 'fa-right-left',
        'title' => 'Transactions | Africo Cash',
        'description' => 'Envoi d’argent, dépôts, retraits, conversions et historique transactionnel.',
        'view' => 'app/views/transactions.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/transactions.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/transactions/transactions.js']),
        'section' => 'app',
    ],
    'mobile_money' => [
        'path' => '/mobile-money',
        'label' => 'Mobile Money',
        'icon' => 'fa-mobile-screen-button',
        'title' => 'Mobile Money | Africo Cash',
        'description' => 'Interopérabilité Airtel Money, M-Pesa, Orange Money et Afrimoney.',
        'view' => 'app/views/mobile_money.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/mobile_money.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/mobile_money/mobile_money.js']),
        'section' => 'app',
    ],
    'banking' => [
        'path' => '/banques',
        'label' => 'Banques',
        'icon' => 'fa-building-columns',
        'title' => 'Banques | Africo Cash',
        'description' => 'Virements entrants, virements sortants, vérification de comptes et réconciliation bancaire.',
        'view' => 'app/views/banking.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/banking.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/banking/banking.js']),
        'section' => 'app',
    ],
    'atm' => [
        'path' => '/atm',
        'label' => 'ATM',
        'icon' => 'fa-money-bill-transfer',
        'title' => 'Retrait ATM | Africo Cash',
        'description' => 'Retrait ATM sans carte avec code temporaire, validation et expiration automatique.',
        'view' => 'app/views/atm.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/atm.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/atm/atm.js']),
        'section' => 'app',
    ],
    'dab' => [
        'path' => '/DAB',
        'label' => 'DAB',
        'icon' => 'fa-money-bills',
        'title' => 'DAB interactif | Africo Cash',
        'description' => 'Simulation de distributeur automatique Africo Cash avec retrait validé via API.',
        'view' => 'app/views/dab.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/dab.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/dab/dab.js']),
        'section' => 'app',
    ],
    'ussd' => [
        'path' => '/USSD',
        'label' => 'USSD',
        'icon' => 'fa-mobile-screen',
        'title' => 'USSD interactif | Africo Cash',
        'description' => 'Simulation de téléphone USSD Africo Cash avec clavier numérique et réponses API.',
        'view' => 'app/views/ussd.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/ussd.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/ussd/ussd.js']),
        'section' => 'app',
    ],
    'bills' => [
        'path' => '/factures',
        'label' => 'Factures',
        'icon' => 'fa-file-invoice-dollar',
        'title' => 'Factures | Africo Cash',
        'description' => 'Paiement de factures universités, télévision, internet, eau et électricité.',
        'view' => 'app/views/bills.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/bills.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/bills/bills.js']),
        'section' => 'app',
    ],
    'profile' => [
        'path' => '/profil',
        'label' => 'Profil',
        'icon' => 'fa-user-shield',
        'title' => 'Profil | Africo Cash',
        'description' => 'Gestion du profil, des paramètres de sécurité et des notifications.',
        'view' => 'app/views/profile.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/profile.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/profile/profile.js']),
        'section' => 'app',
    ],
    'admin' => [
        'path' => '/admin',
        'label' => 'Admin',
        'icon' => 'fa-screwdriver-wrench',
        'title' => 'Administration | Africo Cash',
        'description' => 'Espace de gestion pour utilisateurs, agents, partenaires, taux et commissions.',
        'view' => 'app/views/admin.php',
        'styles' => array_merge($defaultAppStyles, ['/assets/css/views/admin.css']),
        'scripts' => array_merge($defaultAppScripts, ['/assets/js/views/admin/admin.js']),
        'section' => 'app',
    ],
    'not_found' => [
        'path' => '/404',
        'label' => 'Page introuvable',
        'title' => 'Page introuvable | Africo Cash',
        'description' => 'La page demandée est introuvable.',
        'view' => 'app/views/not_found.php',
        'styles' => ['/assets/css/views/not_found.css'],
        'scripts' => ['/assets/js/views/not_found/not_found.js'],
    ],
];
